/**
 * AUTO-GENERATED by packages/shared/scripts/seed-rosters.ts
 * Source of truth: packages/shared/src/data/*.csv (D-01)
 * Regenerate: pnpm run seed:rosters (D-02 — dev tool, not a build step)
 *
 * Phase 19: Replaces TEAM_SQUADS + FREE_AGENTS with PLAYER_POOL: readonly PoolPlayer[].
 * Task 1 stub — empty PLAYER_POOL placeholder until seed script runs in Task 3.
 * TEAM_CONFIGS.playerIds will be populated from seed output in Task 3.
 */
import type { HexCoord } from './types.js';

/** Phase 19 DATA-01/D-07: Pool player with sourceTeamId annotation.
 * Replaces PlayerPiece's teamId ('home'|'away') with sourceTeamId (squad origin).
 * Fields match PlayerPiece stats minus teamId (set at runtime by buildSquadPieces).
 * heading field intentionally omitted — D-01 (Phase 17): heading removed from PlayerPiece. */
export interface PoolPlayer {
  /** Sequential pool ID: p001, p002, ... — assigned by seed script, stable. */
  id: string;
  /** Squad of origin — ColorSchemeId values for legacy squads; team slug for MLS/national; 'free-agent'.
   * Typed as string (wide) per A4 — tightened to a closed union in Phase 21 when all slugs are known. */
  sourceTeamId: string;
  firstName: string;
  lastName: string;
  /** Jersey number within source squad (1–11 per squad). */
  number: number;
  nationality: string;
  role: 'GK' | 'DEF' | 'MID' | 'FWD' | 'ST';
  /** D-02: Formation position placeholder — no algorithmic role until Phase 24. */
  position: HexCoord;
  pace: number;
  shooting: number;
  tackling: number;
  dribbling: number;
  saving: number;
  handling: number;
  resilience: number;
  /** D-13: Fixed "Arial Ability" → "Aerial Ability" typo in all CSVs and seed script. */
  aerialAbility: number;
  highPass: number;
}

/** DATA-01/D-12: Single unified player pool — replaces TEAM_SQUADS and FREE_AGENTS.
 * Task 1 stub: empty until seed script runs in Task 3. */
export const PLAYER_POOL: readonly PoolPlayer[] = [];
